
name: Deploy table

on:
  workflow_dispatch:
  
jobs:
  create_table:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install snowflake-cli
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          
      - name: Configure Snow CLI
        run: |
          snow config set --account--name ${{ secrets.SF_ACCOUNT }}\
            --username ${{ secrets.SF_USER }}\
            --password ${{ secrets.SF_PSWD }}\
            --database ${{ secrets.SF_DB }}\
            --warehouse ${{ secrets.SF_WH }}
      
      - name: Execute SQL file
        run: snow sql -f demo_table.sql
