
name: Deploy table in dev

on:
  workflow_dispatch:
  
jobs:
  create_table:
    environment: dev
    env:
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_USER: ${{ secrets.SF_USER }}
      SF_PSWD: ${{ secrets.SF_PSWD }}
      SF_DB: ${{ secrets.SF_DB }}
      SF_WH: ${{ secrets.SF_WH }}
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install snowflake-cli
        run: pip install snowflake-cli

      - name: Configure snowflake connection
        run: |
          snow connection add defaultv\
          --account $SF_ACCOUNT \
          --username $SF_USER \
          --password $SF_PSWD \
          --warehouse $SF_WH \
          --database $SF_DB
          
      - name: Execute SQL file
        run: |
          snow sql -f demo_table.sql
