
name: Deploy table in dev

on:
  workflow_dispatch:
  
jobs:
  create_table:
    environment: dev
    env:
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_USER: ${{ secrets.SF_USER }}
      SF_PSWD: ${{ secrets.SF_PSWD }}
      SF_DB: ${{ secrets.SF_DB }}
      SF_WH: ${{ secrets.SF_WH }}
      SF_SCHEMA: ${{ secrets.SF_SCHEMA }}
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install snowflake-cli
        run: pip install snowflake-cli

      - name: Create snowcli config file
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/config.toml
          [default]
          account="$SF_ACCOUNT"
          user="$SF_USER"
          password="$SF_PSWD"
          database="$SF_DB"
          warehouse="$SF_WH"
          schema="$SF_SCHEMA"

      - name: Execute SQL file
        run: |
          snow sql -f demo_table.sql
