
name: Deploy table in dev

on:
  workflow_dispatch:
  
jobs:
  create_table:
    environment: dev
    env:
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_USER: ${{ secrets.SF_USER }}
      SF_PSWD: ${{ secrets.SF_PSWD }}
      SF_DB: ${{ secrets.SF_DB }}
      SF_WH: ${{ secrets.SF_WH }}
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install snowflake-cli
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"

      - name: Configure Snow cli
        run: |
          snow configure set database $SF_DB

      - name: Execute SQL file
        run: |
          snow sql -f demo_table.sql
