
name: Deploy table in dev

on:
  workflow_dispatch:
  
jobs:
  create_table:
    environment: dev
    env:
      SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
      SF_USER: ${{ secrets.SF_USER }}
      SF_PSWD: ${{ secrets.SF_PSWD }}
      SF_DB: ${{ secrets.SF_DB }}
      SF_WH: ${{ secrets.SF_WH }}
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install snowflake-cli
        uses: pip install snowflake-cli

      - name: Configure database
        run: |
          snow sql -q "
            USE DATABASE $SF_DB;
          "
          snow sql -f demo_table.sql
